#!/usr/bin/env node

var concat = require('concat-stream'),
    argv = require('minimist')(process.argv.slice(1)),
    fs = require('fs'),
    doxme = require('./index.js');

process.stdin.pipe(concat(function(json) {
    var data = JSON.parse(json), pkg, hasTravis;
    if (argv.readme) {
        pkg = JSON.parse(fs.readFileSync('package.json'));
        hasTravis = fs.existsSync('.travis.yml');
        console.log(doxme(data, argv.readme, pkg, hasTravis));
    } else {
        console.log(doxme(data));
    }
}));
